POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Finnish are nice people, but they are just different",
    "author": "Son To",
    "url": "https://localhost:3000.com"
}